package com.winson.jvm.classreader.service

import java.io.DataInputStream

/**
 * Created by Wei on 2017/6/29.
 */


data class AccType(val value: Int, val name: String) {}

/*
ACC_PUBLIC	0x0001	Declared public; may be accessed from outside its package.
ACC_FINAL	0x0010	Declared final; no subclasses allowed.
ACC_SUPER	0x0020	Treat superclass methods specially when invoked by the invokespecial instruction.
ACC_INTERFACE	0x0200	Is an interface, not a class.
ACC_ABSTRACT	0x0400	Declared abstract; must not be instantiated.
ACC_SYNTHETIC	0x1000	Declared synthetic; not present in the source code.
ACC_ANNOTATION	0x2000	Declared as an annotation type.
ACC_ENUM	0x4000	Declared as an enum type.
 */
private val class_access_flags = listOf(
        AccType(0x4000, "enum"),
        AccType(0x2000, "annotation"),
        AccType(0x1000, "synthetic"),
        AccType(0x0400, "abstract"),
        AccType(0x0200, "interface"),
        AccType(0x0020, "super"),
        AccType(0x0010, "final"),
        AccType(0x0001, "public")
)

/*
ACC_PUBLIC	0x0001	Declared public; may be accessed from outside its package.
ACC_PRIVATE	0x0002	Declared private; usable only within the defining class.
ACC_PROTECTED	0x0004	Declared protected; may be accessed within subclasses.
ACC_STATIC	0x0008	Declared static.
ACC_FINAL	0x0010	Declared final; never directly assigned to after object construction (JLS §17.5).
ACC_VOLATILE	0x0040	Declared volatile; cannot be cached.
ACC_TRANSIENT	0x0080	Declared transient; not written or read by a persistent object manager.
ACC_SYNTHETIC	0x1000	Declared synthetic; not present in the source code.
ACC_ENUM	0x4000	Declared as an element of an enum.
 */

/*
ACC_PUBLIC	0x0001	Declared public; may be accessed from outside its package.
ACC_PRIVATE	0x0002	Declared private; accessible only within the defining class.
ACC_PROTECTED	0x0004	Declared protected; may be accessed within subclasses.
ACC_STATIC	0x0008	Declared static.
ACC_FINAL	0x0010	Declared final; must not be overridden (§5.4.5).
ACC_SYNCHRONIZED	0x0020	Declared synchronized; invocation is wrapped by a monitor use.
ACC_BRIDGE	0x0040	A bridge method, generated by the compiler.
ACC_VARARGS	0x0080	Declared with variable number of arguments.
ACC_NATIVE	0x0100	Declared native; implemented in a language other than Java.
ACC_ABSTRACT	0x0400	Declared abstract; no implementation is provided.
ACC_STRICT	0x0800	Declared strictfp; floating-point mode is FP-strict.
ACC_SYNTHETIC	0x1000	Declared synthetic; not present in the source code.
 */
private val method_access_flags = listOf(
        AccType(0x1000, "synthetic"),
        AccType(0x0800, "strict"),
        AccType(0x0400, "abstract"),
        AccType(0x0100, "native"),
        AccType(0x0080, "varargs"),
        AccType(0x0040, "bridge"),
        AccType(0x0020, "synchronized"),
        AccType(0x0010, "final"),
        AccType(0x0008, "static"),
        AccType(0x0004, "protected"),
        AccType(0x0002, "private"),
        AccType(0x0001, "public")
)

fun readClassAccessFlags(input: DataInputStream) {
    readClassAccessFlags(input, class_access_flags)
}

fun readMethodAccessFlags(input: DataInputStream) {
    readClassAccessFlags(input, method_access_flags)
}

private fun readClassAccessFlags(input: DataInputStream, allPosibleAcc: List<AccType>) {
    var accessAsInt = input.readUnsignedShort()

    for (acc in allPosibleAcc) {
        if (accessAsInt >= acc.value) {
            print(" ${acc.name}")
            accessAsInt -= acc.value
        }
    }
}
